# AIS Prometheus Configuration

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ais-api'
    static_configs:
      - targets: ['ais-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 4s

  - job_name: 'ais-loop'
    static_configs:
      - targets: ['ais-loop:9002']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 4s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
    scrape_interval: 15s
